### ISSUE TITLE
/portal/mix-database-data/list > Migrate error

### ISSUE THREAD

**Issue by Smilefounder** [mixcore/mix.core#407]
![image](https://user-images.githubusercontent.com/3785721/123552025-802a6a00-d79e-11eb-85f9-48616c342e05.png)

```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: mixdb_sys_navigation'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at Mix.Cms.Lib.ViewModels.MixDatabaseDatas.Helper.MigrateData(Int32 databaseId) in D:\mixcore\mix.core\src\Mix.Cms.Lib\ViewModels\MixDatabaseDatas\Helper.cs:line 991
   at Mix.Cms.Api.RestFul.Controllers.v1.MixDatabaseDataPortalController.MigrateData(Int32 databaseId) in D:\mixcore\mix.core\src\Mix.Cms.Api.RestFul\Controllers\v1\MixDatabaseDatas\MixDatabaseDataPortalController.cs:line 203
   at lambda_method8164(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Pragma: no-cache
:authority: localhost:5001
:method: GET
:path: /api/v1/rest/en-us/mix-database-data/portal/migrate-data/2
:scheme: https
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,vi;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdXBlckFkbWluIiwiSWQiOiIwY2VlZDU2MC1hM2RkLTQzMDctYWU2ZS04ZDIzOTdkNDRlMzciLCJVc2VybmFtZSI6ImFkbWluIiwiUmVmcmVzaFRva2VuIjoiMTE2NGFiZWUtMGI1MC00NGM4LWJlMTgtNDZmNzNmODcxMGFjIiwiQUVTS2V5IjoiY0N0Rk5YSkVlR3d6VWpsM1YzUnpaR2t2WkZReFFUMDlMR1UyY3pjMlRTdG5SMWd5ZURBNWJuWjRkMmRwWkhjek9GRk1kRVZ2ZVhaeVNWRlRLMlZVYXpkWVZYTTkiLCJSU0FQdWJsaWNLZXkiOiI8P3htbCB2ZXJzaW9uPVwiMS4wXCIgZW5jb2Rpbmc9XCJ1dGYtMTZcIj8-XHJcbjxSU0FQYXJhbWV0ZXJzIHhtbG5zOnhzaT1cImh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlXCIgeG1sbnM6eHNkPVwiaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWFcIj5cclxuICA8RXhwb25lbnQ-QVFBQjwvRXhwb25lbnQ-XHJcbiAgPE1vZHVsdXM-M2JGaXZTUjRWbTJCS2w1QTVwbHlZK0t0VURubEQrRGtpSEkwZTBLa0pDakN1eWswUUd0TFN3dElHVTRsT3ozMVFFcXUvbUVvOFMxc29tUXErSFZyR3hFTTZpR2VySlZKUVZaUHJZcVkyNlhXWDg0NEZ6TjRFYjJTa0EwaUlUdEFiZ1pCUjZySytidnl1VkZnN1A0dDhzRHpaWThlWDF4Z3AxRFRjbVhTUUliMDVnZXlkVHNMcmthdDdsZWtya2hhaktseVZTTm1ZZTdUYzJ6K294WjdwWHI0am1jTHUvY3dTSDdoV3Y3V3V5MHpGSWhmSG4ra0VVKzI3TkpCWjdRMEpOVW55V3dsRVBCZFNndVIxOHFKdGgxUDJKZyt2cjRKaGpQTS81d0xZOE81WG1aZEcyYXh6Q0RCQVpweWQxM0tQUC9raSthZ2ZwblJicXlOSEI3OFJRPT08L01vZHVsdXM-XHJcbjwvUlNBUGFyYW1ldGVycz4iLCJuYmYiOjE2MjQ4MTA0NzQsImV4cCI6MTYyNDgxMTY3NCwiaXNzIjoibWl4LWNvcmUiLCJhdWQiOiJtaXgtY29yZSJ9.SU5twN50eqeZtFYWpv8kJ-yofr1KFmJebPxQRNc_bvo
Cookie: .AspNetCore.Identity.Application=CfDJ8L-j8H6gqcxDi8xTvR8wqEuxHKviEVbXkL5Pj01Xcf1sBxqmSkNcPhUnmCiPWbMDWyaZmvVHNXFIZpVemytdYkfUEcMBRt6bNRe3GnbcFqO3QM8leh9hmWtxX0N7muxqu0K19EZoFCICK8M2Ha7FOkoZwNbyfSuw1m0PetG3p3IFUapC16iu1xRRh_CijJjzDb8vpXZUbN5lueo8iclBHpGqa8uYNsvzyFOwCf7mRT7pbLXmtGznCm4v95zxfChn3f8axnOqzTsuyKWH37N8QOvaUcayEhDpDnkdB0ZvTHhtlpvc-xrnhbvOX5TzzgPy0H8GyP0qVbki4GRdOoIVvGluwTOG2Esim-vHibqI0Xh7QrEZ-1imn2I5efNugXzEfamAvFnhaIxUSL1VUOwk-x57rWaC-fqVBUn9H1Kus4XTl_j7HkwUzT4Dvj2Hj0LkKC59MD3zAOCEMkOlNyior_qAmVf5GH7REDs4E28UmpDGmf7N0DGc7JDZHhfw6DgdUNTLKXak5MuwkjIkRTpjXLeIART2G0O_tOZ_lPdtGMRAft8Lf87_MkXunrjYw8eGXZdy3qLJxww1v92BWOPec4BgR0mS0UPIo8X1MtrRbaS8E0mk1BBVUtBV9NxLv6_Ed6qGj6z4sQeEQ-CahLNxyWP4YMo1peZYaydQ-uZ5o8QpmNbuoiyQ313k1INji8_rguV-IrXpytZX25OWhTXAwnXEHNNImbqj7v5oxfwIq-1zt6PscOLe1qT9kchjgsueDqIsAeFbS86ljb7Knc-OoQmcISlxkAFJZ8r87mEYIiptsscg3ghxjTMDcFQIQ8IgSEZ0bW-DX37qFBVXmGPhFKE
Host: localhost:5001
Referer: https://localhost:5001/portal/mix-database-data/list?mixDatabaseId=2&mixDatabaseName=sys_navigation&mixDatabaseTitle=Navigation
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54
sec-ch-ua: " Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
`

**Comment by nhathoang989** [comment]
Fixed #409
