### ISSUE TITLE
Unhandled Exception: System.FormatException: Could not parse the JSON file. Error on line number '0': ''. ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by Smilefounder** [mixcore/mix.core#47]
Step to reproduce:
1. dotnet run in the command line
2. Load to init page
3. Do nothing, close command line
4. dotnet run again

```
Unhandled Exception: System.FormatException: Could not parse the JSON file. Error on line number '0': ''. ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Mix.Cms.Web.Program.Main(String[] args) in E:\_Workspace\Github\mixcore\mix.core\src\Mix.Cms.Web\Program.cs:line 13
```

**Comment by Smilefounder** [comment]
Fixed in the latest code.
